name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # publish releases

jobs:
  publish-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.10
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build and publish Win artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm build && pnpm exec electron-builder --win --publish always
